# Generated by Django 5.0.1 on 2025-05-08 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMIRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('initial_bmi', models.FloatField(default=0)),
                ('current_bmi', models.FloatField()),
                ('category', models.CharField(choices=[('Underweight', 'Underweight'), ('Normal', 'Normal'), ('Overweight', 'Overweight'), ('Obese', 'Obese')], default='Normal', max_length=20)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MoodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('mood', models.CharField(choices=[('Happy', 'Happy 😊'), ('Normal', 'Normal 😐'), ('Sad', 'Sad 😢'), ('Awful', 'Awful 😡')], default='Normal', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('sleep_duration', models.FloatField()),
                ('sleep_quality', models.CharField(choices=[('Excellent', 'Excellent 🌟'), ('Good', 'Good 🙂'), ('Fair', 'Fair 😐'), ('Poor', 'Poor 😴')], default='Good', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
