# Generated by Django 5.1.7 on 2025-03-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieDeficitPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('target_date', models.DateField()),
                ('target_weight', models.FloatField(default=0)),
                ('daily_caloric_intake', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(choices=[('Aerobic', 'Aerobic'), ('Anaerobic', 'Anaerobic')], max_length=20)),
                ('total_caloric_intake', models.IntegerField(default=0)),
                ('recommended_exercise', models.TextField(default='Exercise')),
                ('calories_burned', models.IntegerField(default=0)),
                ('duration', models.DurationField(default='00:05:00')),
            ],
        ),
        migrations.CreateModel(
            name='FastingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('fasting_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IntermittentFastingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasting_type', models.CharField(choices=[('18:6', '18:6'), ('16:8', '16:8'), ('OMAD', 'One Meal A Day')], max_length=10)),
                ('eating_window_start', models.TimeField()),
                ('eating_window_end', models.TimeField()),
                ('fasting_window_start', models.TimeField()),
                ('fasting_window_end', models.TimeField()),
            ],
        ),
    ]
