# Generated by Django 5.1.7 on 2025-04-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessPlanning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caloriedeficitplanner',
            name='current_weight',
            field=models.FloatField(default=0),
        ),
    ]
