# Generated by Django 5.1.7 on 2025-03-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
