# Generated by Django 5.1.6 on 2025-05-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_user_acid_peptic_disorder_user_alcohol_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allergy_name',
            field=models.CharField(blank=True, default='Sesame', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_caloric_intake',
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
    ]
